

try
{

}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}

Console.Write("Finished!");
Console.Read();
